# Generated by Django 3.2.12 on 2022-04-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdrf', '0002_alter_book_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
