# Generated by Django 3.2.12 on 2022-05-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdrf', '0004_book_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='pub_date',
        ),
    ]
