# Generated by Django 3.2.9 on 2021-12-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nikename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
