# Generated by Django 3.2.9 on 2021-12-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0004_auto_20211226_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nikename',
            new_name='nickname',
        ),
    ]
