# Generated by Django 3.2.9 on 2022-01-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0009_auto_20220103_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='123@126.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default='12'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='useradmin.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Jone', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Jone', max_length=50),
        ),
    ]
