# Generated by Django 3.1.7 on 2021-04-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.organization'),
        ),
    ]
