# Generated by Django 3.1.7 on 2021-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='orgname',
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
