# Generated by Django 3.1.7 on 2021-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0006_auto_20210410_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(db_column='hname', max_length=30),
        ),
    ]
