# Generated by Django 3.1.7 on 2021-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0007_auto_20210410_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('tage', models.IntegerField(max_length=10)),
            ],
        ),
    ]
