# Generated by Django 3.1.7 on 2021-04-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0008_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='writer',
        ),
        migrations.AlterField(
            model_name='writer',
            name='tage',
            field=models.IntegerField(),
        ),
    ]
