# Generated by Django 3.1.7 on 2021-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0010_auto_20210417_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('wid', models.IntegerField()),
            ],
        ),
    ]
