# Generated by Django 3.2.12 on 2022-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0011_book_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
